[project]
name = "sxjm"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "caobaoqi6040", email = "caobaoqi6040@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
]

[project.scripts]
sxjm = "sxjm:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
